version: '3.5'

services:
  coffee_api:
    build: .
    volumes:
      - .:/app
    ports:
      - 5000:5000
    depends_on:
      - db

  db:
    image: postgres
    env_file: database.conf
    ports:
      - 5432:5432
