version: '3'

services:
  coffee_api:
    build: .
    volumes:
      - .:/app
    ports:
      - 5000:5000
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: root
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
